import type { LanguageInfo } from "./types";

// Curated from GitHub Linguist language names, colors, extensions, and common filenames.
export const LANGUAGE_BY_EXTENSION: Record<string, LanguageInfo> = {
  astro: { color: 0xff5a03, name: "Astro" },
  bash: { color: 0x89e051, name: "Shell" },
  bat: { color: 0xc1f12e, name: "Batchfile" },
  c: { color: 0x555555, name: "C" },
  cc: { color: 0xf34b7d, icon: "cpp", name: "C++" },
  clj: { color: 0xdb5855, name: "Clojure" },
  cljs: { color: 0xdb5855, name: "Clojure" },
  cmake: { color: 0xda3434, name: "CMake" },
  coffee: { color: 0x244776, name: "CoffeeScript" },
  cpp: { color: 0xf34b7d, icon: "cpp", name: "C++" },
  cs: { color: 0x178600, icon: "csharp", name: "C#" },
  css: { color: 0x663399, icon: "css", name: "CSS" },
  dart: { color: 0x00b4ab, name: "Dart" },
  dockerfile: { color: 0x384d54, name: "Dockerfile" },
  eex: { color: 0x6e4a7e, name: "Elixir" },
  elm: { color: 0x60b5cc, name: "Elm" },
  erl: { color: 0xb83998, name: "Erlang" },
  ex: { color: 0x6e4a7e, name: "Elixir" },
  exs: { color: 0x6e4a7e, name: "Elixir" },
  fs: { color: 0xb845fc, name: "F#" },
  fsx: { color: 0xb845fc, name: "F#" },
  gd: { color: 0x355570, name: "GDScript" },
  go: { color: 0x00add8, icon: "go", name: "Go" },
  gql: { color: 0xe10098, name: "GraphQL" },
  graphql: { color: 0xe10098, name: "GraphQL" },
  groovy: { color: 0x4298b8, name: "Groovy" },
  h: { color: 0xa8b9cc, name: "C/C++ Header" },
  hcl: { color: 0x844fba, name: "HCL" },
  heex: { color: 0x6e4a7e, name: "Elixir" },
  hpp: { color: 0xf34b7d, icon: "cpp", name: "C++" },
  hs: { color: 0x5e5086, name: "Haskell" },
  htm: { color: 0xe34c26, icon: "html", name: "HTML" },
  html: { color: 0xe34c26, icon: "html", name: "HTML" },
  java: { color: 0xb07219, icon: "java", name: "Java" },
  jl: { color: 0xa270ba, name: "Julia" },
  js: { color: 0xf1e05a, icon: "javascript", name: "JavaScript" },
  json: { color: 0x292929, name: "JSON" },
  json5: { color: 0x267cb9, name: "JSON5" },
  jsonc: { color: 0x292929, name: "JSON with Comments" },
  jsx: { color: 0xf1e05a, icon: "javascript", name: "JavaScript" },
  kt: { color: 0xa97bff, icon: "kotlin", name: "Kotlin" },
  kts: { color: 0xa97bff, icon: "kotlin", name: "Kotlin" },
  less: { color: 0x1d365d, name: "Less" },
  liquid: { color: 0x67b8de, name: "Liquid" },
  lua: { color: 0x000080, icon: "lua", name: "Lua" },
  m: { color: 0x438eff, name: "Objective-C" },
  md: { color: 0x083fa1, icon: "markdown", name: "Markdown" },
  mjs: { color: 0xf1e05a, icon: "javascript", name: "JavaScript" },
  mm: { color: 0x438eff, name: "Objective-C++" },
  nim: { color: 0xffc200, name: "Nim" },
  nix: { color: 0x7e7eff, name: "Nix" },
  php: { color: 0x4f5d95, icon: "php", name: "PHP" },
  pl: { color: 0x0298c3, name: "Perl" },
  pm: { color: 0x0298c3, name: "Perl" },
  ps1: { color: 0x012456, name: "PowerShell" },
  psm1: { color: 0x012456, name: "PowerShell" },
  pug: { color: 0xa86454, name: "Pug" },
  py: { color: 0x3572a5, icon: "python", name: "Python" },
  r: { color: 0x198ce7, name: "R" },
  rb: { color: 0x701516, icon: "ruby", name: "Ruby" },
  res: { color: 0xed5051, name: "ReScript" },
  rs: { color: 0xdea584, icon: "rust", name: "Rust" },
  sass: { color: 0xa53b70, name: "Sass" },
  scala: { color: 0xc22d40, name: "Scala" },
  scss: { color: 0xc6538c, name: "SCSS" },
  sh: { color: 0x89e051, name: "Shell" },
  sql: { color: 0xe38c00, name: "SQL" },
  svelte: { color: 0xff3e00, name: "Svelte" },
  swift: { color: 0xf05138, icon: "swift", name: "Swift" },
  tf: { color: 0x844fba, name: "Terraform" },
  toml: { color: 0x9c4221, name: "TOML" },
  ts: { color: 0x3178c6, icon: "typescript", name: "TypeScript" },
  tsx: { color: 0x3178c6, icon: "typescript", name: "TypeScript" },
  vue: { color: 0x41b883, name: "Vue" },
  xml: { color: 0x0060ac, name: "XML" },
  yaml: { color: 0xcb171e, name: "YAML" },
  yml: { color: 0xcb171e, name: "YAML" },
  zig: { color: 0xec915c, name: "Zig" },
  zsh: { color: 0x89e051, name: "Shell" },
};

export const LANGUAGE_BY_FILENAME: Record<string, LanguageInfo> = {
  ".babelrc": { color: 0xf1e05a, icon: "javascript", name: "JavaScript" },
  ".dockerignore": { color: 0x384d54, name: "Dockerfile" },
  ".eslintrc": { color: 0x4b32c3, name: "ESLint" },
  ".gitattributes": { color: 0xf44d27, name: "Git Attributes" },
  ".gitignore": { color: 0xf44d27, name: "Git Ignore" },
  ".prettierrc": { color: 0x1a2b34, name: "Prettier" },
  "bun.lock": { color: 0xf9f1e1, name: "Bun" },
  "cargo.lock": { color: 0xdea584, icon: "rust", name: "Rust" },
  "cargo.toml": { color: 0xdea584, icon: "rust", name: "Rust" },
  "cmakelists.txt": { color: 0xda3434, name: "CMake" },
  "composer.json": { color: 0x4f5d95, icon: "php", name: "PHP" },
  dockerfile: { color: 0x384d54, name: "Dockerfile" },
  gemfile: { color: 0x701516, icon: "ruby", name: "Ruby" },
  "go.mod": { color: 0x00add8, icon: "go", name: "Go" },
  "go.sum": { color: 0x00add8, icon: "go", name: "Go" },
  makefile: { color: 0x427819, name: "Makefile" },
  "package-lock.json": { color: 0xf1e05a, icon: "javascript", name: "JavaScript" },
  "package.json": { color: 0xf1e05a, icon: "javascript", name: "JavaScript" },
  "pnpm-lock.yaml": { color: 0xf69220, name: "PNPM" },
  "pom.xml": { color: 0xb07219, icon: "java", name: "Java" },
  procfile: { color: 0x6762a6, name: "Procfile" },
  "pyproject.toml": { color: 0x3572a5, icon: "python", name: "Python" },
  "requirements.txt": { color: 0x3572a5, icon: "python", name: "Python" },
  "tsconfig.json": { color: 0x3178c6, icon: "typescript", name: "TypeScript" },
  "yarn.lock": { color: 0x2c8ebb, name: "Yarn" },
};
